name: Java CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & test
        run: mvn -q verify

      - name: Run benchmark (optional)
        run: mvn -q compile exec:java -Dexec.mainClass="cli.BenchmarkRunner" -Dexec.args="100 1000 5000"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: heapsort-results
          path: results_heapsort.csv
